### ISSUE TITLE
issues with npm run backend

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#138]
I'm running npm run backend but it's telling me:
```
(node:65144) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
connection error: { MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]
    at Pool.<anonymous> (/Users/joannakatsifaraki/src/the-travel-shelf/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (/Users/joannakatsifaraki/src/the-travel-shelf/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (/Users/joannakatsifaraki/src/the-travel-shelf/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]' }

```
I also did npm install and got 
```
npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 20.359s
```
Can't get the server to work so I can see my work. 
Can you help @VernL 
Thanks!

**Comment by Jojokats** [comment]
Would like to test my code before merging

**Comment by VernL** [comment]
I have shared a .env (That's (dot)env) via google drive. This file contains the login credentials for the database and needs to be created and placed in the project's root directory.

**Comment by Jojokats** [comment]
Thanks @VernL , I downloaded your file and placed it in the root, but is still won't work

**Comment by VernL** [comment]
The file on google drive was automatically renamed to env. The project expects a file called (dot)env. You must create a file called (dot)env and place the content from the env file inside.

**Comment by VernL** [comment]
We are already having this discussion on slack...

**Comment by VernL** [comment]
The file must be called (dot)env.

**Comment by Jojokats** [comment]
yeah I have one

**Comment by Jojokats** [comment]
I did a npm install and then npm run backend but it still won't work. Getting errors
```
(node:66841) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
connection error: { MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]
    at Pool.<anonymous> (/Users/joannakatsifaraki/src/the-travel-shelf/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (/Users/joannakatsifaraki/src/the-travel-shelf/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (/Users/joannakatsifaraki/src/the-travel-shelf/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]' }



```

**Comment by VernL** [comment]
Solved?

**Comment by Jojokats** [comment]
yup
